# Generated by Django 5.0.6 on 2024-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_remove_lesson_doc_upload_remove_lesson_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='doc_upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
