# Generated by Django 5.0.6 on 2024-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_lesson_npid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='npid',
            field=models.CharField(max_length=100),
        ),
    ]
