# Generated by Django 5.0.6 on 2024-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0005_alter_lesson_npid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hasResources',
            field=models.BooleanField(default=False),
        ),
    ]
